name: Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.1"

      - name: Install dependency
        run: go get -t -v ./...

      - name: Test
        run: |
          bash scripts/gen-valid-cert.sh
          bash scripts/gen-chain-cert.sh
          bash scripts/gen-ocsp-cert.sh
          go test -v ./...
